set(VCPKG_TARGET_TRIPLET wasm32-emscripten)
set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CXX_FLAGS "-pthread")
set(VCPKG_C_FLAGS "-pthread")
